models/subject.py
from flask import *
from app import app , mysql
from models import user 
from views import subject_route


def room_pass_check(roomID , Entered_password , mysql):
    cur = mysql.connection.cursor()
    res = cur.execute("SELECT id from chat.rooms where  id= %s and password = %s" , [roomID, Entered_password] )
    data = cur.fetchone()
    # print('room_pass_check :  ' , data)
    if data:
        return True
    else:
        return False

def user_Room_Permission(id,  mysql):
    cur = mysql.connection.cursor()
    res = cur.execute("SELECT id from chat.room_right where user_id = %s and room_id = %s" , [session['id'], id] )
    data = cur.fetchone()
    # print('user_Room_Permission :  ' , data)
    if data:
        return True
    else:
        return False

def isPermissionReq(id , mysql):
    cur = mysql.connection.cursor()
    res = cur.execute("SELECT require_permission from chat.rooms where id = %s" , [id] )
    data = cur.fetchone()[0] 
    print('data : ' , data)
    if data == 0:
        return False
    else:
        return True


def getSubjectsData(self):
    cur = mysql.connection.cursor()
    sql = "SELECT id ,room_name , require_permission from chat.rooms"
    res = cur.execute(sql)
    data = cur.fetchall() 
    return data


def getRoom(id , mysql):
    curr = mysql.connection.cursor()
    sql = "SELECT * from chat.rooms"
    res = curr.execute(sql)
    data = curr.fetchone()[0]
    print("id : " , id)
    return data 



def isSecret(subject_id , mysql):
    curr = mysql.connection.cursor()
    res = curr.execute("SELECT COUNT(*)  from  chat.rooms where id = %s and require_permission = 1 " ,[subject_id])
    data = curr.fetchall()[0]
    return data[0] > 0


def hasRight( subject_id ,mysql):
    user_id = session['id']
    if session['admin']:
       return True 
    else:
        if isSecret(subject_id , mysql):
            curr = mysql.connection.cursor()
            res = curr.execute( "SELECT COUNT(*)  from  chat.room_right where room_id = %s and  user_id = %s" , [subject_id,user_id])
            data = curr.fetchone()[0]

            if data > 0 :   
                print("user has right.......")
                return True 
            else :
                print("User do not have right.......")
                return False
        else:
            return True 
                       
def add_right(user_id , subject_name , mysql):
    try:
        cur  = mysql.connection.cursor()
        cur.execute("""INSERT into chat.room_right (user_id , room_id)
             values (%s,(SELECT id from chat.rooms where room_name = %s ))"""  , [user_id , subject_name])     
        mysql.connection.commit()
    except:
        print("Error while adding rights........." , )    


def create_subject(user_id, subject_name, subject_password, subject_content, subject_require, mysql):
    if subject_password == "":
        subject_password = "1234"
    
    try:
        cur  = mysql.connection.cursor()
        cur.execute("INSERT into chat.rooms (room_name , password , content , require_permission) values (%s,%s,%s,%s)"  , (subject_name, subject_password,subject_content,subject_require))     
        mysql.connection.commit()
    except:
        return False    

    if subject_password != "":
        add_right(session["id"], subject_name, mysql)
        return True

def findRoomName(roomID,mysql):
        cur = mysql.connection.cursor()
        cur.execute("SELECT room_name from  chat.rooms where id = %s  " , [roomID])
        data = cur.fetchall()[0]
        return data[0] 

views/subject_route.py
from os import name
from app import app
from flask import  *
from werkzeug.exceptions import FailedDependency
from models import subject,user,chat
from flask_mysqldb import MySQL
# from project.models import user

sub_route = Blueprint("sub_route" , __name__)

mysql = MySQL()

@sub_route.route("/rooms")
def subjects():
    subject_data = subject.getSubjectsData(mysql);
    print(subject_data)
    if subject_data:
        return render_template('subjects.html' , subject_data = subject_data   ) 
    else:
        return render_template('subjects.html')


@sub_route.route("/create_sub")
def create_sub():
    return render_template("create_subject.html")


@sub_route.route("/create_subject" ,methods = [ 'GET','POST' ])
def create_subject():
    if request.method == 'POST':
        user_id = session['id']
        subject_name = request.form["subject_name"]
        subject_password = request.form["subject_pass"]
        subject_content = request.form["subject_desc"]
        subject_require = request.form["require"]

        if int(subject_require) == 1 and subject_password == "":
            flash('you must give a password')
            return redirect(request.referrer)

        if subject.create_subject(user_id, subject_name, subject_password, subject_content, subject_require, mysql):
            flash("Room created", "message")
            print("Room created")
            return redirect("/rooms")


        else:
            flash("Error creating subject - name might be taken", "error")
            return redirect(request.referrer)



@sub_route.route("/checkRoomPass" ,methods = [ 'GET','POST' ])
def checkRoomPass():
    if request.method == 'POST':
        user_id = session['id']
        Entered_password = request.form["pass"]
        roomID = request.form["roomID"]
        roomName = subject.findRoomName(roomID,mysql)
        if subject.room_pass_check(roomID, Entered_password, mysql) == True :
            # print('\n\n\n room Name > : ' , roomName)
            new_data = chat.get_messages(roomName,mysql);

            names = []
            time = []
            messages = []
            
            for val in new_data :
                cur  = mysql.connection.cursor()
                cur.execute("SELECT username from chat.user where id = %s" , [val[0]]) 
                USERNAME = cur.fetchone()[0]
                cur.execute("SELECT room_name from chat.rooms where id = %s" , [val[1]])
                ROOMNAME = cur.fetchone()[0]
                names.append(USERNAME)
                time.append(val[3])
                messages.append(val[2])

            return render_template('enterRoom.html' , id = roomID, user = session['username'] ,roomName = roomName,data = zip(names,time,messages))
        else:
            flash('password Incorrect')
            return redirect('/rooms')


@sub_route.route("/enter_room/<int:id>")
def enter_room(id):
    req_permission = subject.isPermissionReq(id , mysql)
    if session['admin'] == True or subject.user_Room_Permission(id,mysql) == True or req_permission == False  :
        roomName = subject.findRoomName(id,mysql)
        new_data = chat.get_messages(roomName,mysql);

        names = []
        time = []
        messages = []
        for val in new_data :
            cur  = mysql.connection.cursor()
            cur.execute("SELECT username from chat.user where id = %s" , [val[0]]) 
            USERNAME = cur.fetchone()[0]
            cur.execute("SELECT room_name from chat.rooms where id = %s" , [val[1]])
            ROOMNAME = cur.fetchone()[0]
            names.append(USERNAME)
            time.append(val[3])
            messages.append(val[2])

        return render_template('enterRoom.html' ,id =  id , user = session['username'] , roomName = roomName , data = zip(names,time,messages))
    else:
        return render_template('roomLogin.html' ,id  = id , fail = 0)

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <title>Home</title>
    <link rel="stylesheet" href="/static/chat.css">

</head>

<body>

    <nav class="navbar sticky-top navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
            <a class="navbar-brand" href="/">
                <h3 id="chat-clicked" style="font-family:cursive;"> CHAT </h3>
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">

                {% if 'username' in session : %}
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="/rooms">
                            <h3 style="font-family:cursive; "> Rooms </h3>
                        </a>
                    </li>
                </ul>
                <form class="d-flex px-1">
                    <a id="logout-now" class="btn btn-outline-danger" type="submit" style="font-family:cursive;"
                        href="/logout">Logout</a>
                </form>

                {% else %}

                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="/login">
                            <h3 class="room-click" style="font-family:cursive;"> Rooms </h3>
                        </a>
                    </li>
                </ul>
                <form class="d-flex">
                    <a class="btn btn-outline-success" type="submit" style="font-family:cursive;"
                        href="/login">Login</a>
                </form>
                <form class="d-flex px-1">
                    <a class="btn btn-outline-danger" type="submit" style="font-family:cursive;"
                        href="/register">Register</a>
                </form>
                {% endif %}

            </div>
        </div>
    </nav>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>

    {% block navbar %}

    {% endblock navbar %}

</body>

</html>

templates/create_subject.html
{% extends 'base.html' %}
{% block navbar %}

<body style="background-color: rgb(34, 33, 33);">

    <h1 class="container text-center " style="color:bisque">Create Room</h1>
    <div class="container bg-white py-5">
        <form action="/create_subject" method="POST">
            <div class="container my-5 ">
                <div class="mb-5">
                    <label for="name" class="form-label">Name</label>
                    <input type="text" class="form-control" id="name" name="subject_name" placeholder="Enter room name"
                        required>
                </div>
                <div class="mb-3">
                    <label for="pass" class="form-label">Description</label>
                    <textarea class="form-control" id="pass" name="subject_desc"
                        placeholder="Enter something...."></textarea>
                </div>
                <div class="mb-3">
                    <p>Requires Password:<br>
                        <label>
                            <input type="radio" id="require_yes" name="require" value="1" required>
                            Yes
                        </label>
                        <label>
                            <input type="radio" id="require_no" name="require" value="0">
                            No
                        </label>
                    </p>
                </div>
                <div class="mb-3">
                    <label for="pass" class="form-label">Password</label>
                    <input type="password" class="form-control" id="pass" name="subject_pass"
                        placeholder="Enter Password" autocomplete="off">
                </div>
                <button class="btn btn-primary my-2" type="submit">Create</button>
            </div>

        </form>

    </div>

    {% endblock navbar %}

</body>

templates/enterRoom.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <title>{{roomName}}</title>
    <link rel="stylesheet" href="/static/chat.css">
    <script src="/static/socket.js"></script>
    <style>
        body {
            background-color: blueviolet;
        }
    </style>
    <script>
        const username = `{{user}}`
        const roomName = `{{roomName}}`

    </script>

</head>

<body>
    <!-- Navbar -->
    <nav class="navbar sticky-top navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
            <a class="navbar-brand" href="/">
                <h3 id="chat-clicked" style="font-family:cursive;"> CHAT </h3>
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">

                {% if 'username' in session : %}
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="/rooms">
                            <h3 class="room-click" style="font-family:cursive; "> Rooms
                            </h3>
                        </a>
                    </li>
                </ul>
                <form class="d-flex px-1">
                    <a id="logout-now" class="btn btn-outline-danger" type="submit" style="font-family:cursive;"
                        href="/logout">Logout</a>
                </form>

                {% else %}

                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="/login">
                            <h3 style="font-family:cursive;"> Rooms </h3>
                        </a>
                    </li>
                </ul>
                <form class="d-flex">
                    <a class="btn btn-outline-success" type="submit" style="font-family:cursive;"
                        href="/login">Login</a>
                </form>
                <form class="d-flex px-1">
                    <a class="btn btn-outline-danger" type="submit" style="font-family:cursive;"
                        href="/register">Register</a>
                </form>
                {% endif %}

            </div>
        </div>
    </nav>

    <!-- Main start here  -->

    <div id="main-section" class="container row-2 py-2">

        <div class="container-lg " style="border:2px solid rgb(1, 1, 3) ; background-color:#f0e9df">
            <!-- Message display -->
            <div class="container" id="display-section">
                <!-- Messages will be here -->
                {% for name,tm,mess in data %}
                {% if name == session['username'] %}
                <div class=" d-block text-end py-1">
                    <p class="my-chat1 d-inline-block rounded-start px-2" style="background-color: rgb(74, 166, 228);">
                        <!-- <span class="fw-bold"> {{name}}</span> -->
                        <br>
                        <span class="message  fw-normal text-white">{{mess}}</span>
                        <br>
                        <span class="fw-light text-white" style="font-size:10px;">{{tm}}</span>
                        <br>
                    </p>
                </div>
                {% else %}
                <div class="d-block text-start py-1">
                    <p class="other-chat1 d-inline-block rounded-bottom  px-2"
                        style="background-color: rgba(157, 161, 163, 0.945);">
                        <span class="fw-bold"> {{name}}</span>
                        <br>
                        <span class="message  fw-normal text-white">{{mess}}</span>
                        <br>
                        <span class="fw-light text-white" style="font-size:10px;">{{tm}}</span>
                        <br>
                    </p>
                </div>
                {% endif %}

                {% endfor %}
                <script>
                    var messageBody = document.querySelector('#display-section');
                    messageBody.scrollTop = messageBody.scrollHeight - messageBody.clientHeight;
                </script>
            </div>

        </div>
    </div>

    <!-- Input here  -->
    <div class="input-group mb-3 container input my-2">
        <input class=" form-control" placeholder="Send message here..." type="text" id="user_message">
        <!-- Send Message -->
        <button class="btn btn-danger" type="submit" id="send_message"><i class="bi bi-send"></i>
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-send"
                viewBox="0 0 16 16">
                <path
                    d="M15.854.146a.5.5 0 0 1 .11.54l-5.819 14.547a.75.75 0 0 1-1.329.124l-3.178-4.995L.643 7.184a.75.75 0 0 1 .124-1.33L15.314.037a.5.5 0 0 1 .54.11ZM6.636 10.07l2.761 4.338L14.13 2.576 6.636 10.07Zm6.787-8.201L1.591 6.602l4.339 2.76 7.494-7.493Z" />
            </svg>
        </button>
    </div>

    <!-- <p>{{user}}</p> -->


    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/socket.io/4.0.1/socket.io.js"
        integrity="sha512-q/dWJ3kcmjBLU4Qc47E4A9kTB4m3wuTY7vkFJDTZKjTs8jhyGQnaUrxa0Ytd0ssMZhbNua9hE+E7Qv1j+DyZwA=="
        crossorigin="anonymous"></script>


</body>

</html>

templates/intro.html
{% extends 'base.html' %}
{% block navbar %}

<body style=" background-color: #7204dada;">
</body>

{% if 'username' in session: %}
<div class="container">
    <h2 class="my-2 "> Welcome <strong style="color: rgb(255, 245, 233);"> {{session['username']}} </strong> </h2>

    <svg xmlns="http://www.w3.org/2000/svg" width="100" height="100" fill="currentColor" class="bi bi-chat my-5"
        viewBox="0 0 16 16">
        <path
            d="M2.678 11.894a1 1 0 0 1 .287.801 10.97 10.97 0 0 1-.398 2c1.395-.323 2.247-.697 2.634-.893a1 1 0 0 1 .71-.074A8.06 8.06 0 0 0 8 14c3.996 0 7-2.807 7-6 0-3.192-3.004-6-7-6S1 4.808 1 8c0 1.468.617 2.83 1.678 3.894zm-.493 3.905a21.682 21.682 0 0 1-.713.129c-.2.032-.352-.176-.273-.362a9.68 9.68 0 0 0 .244-.637l.003-.01c.248-.72.45-1.548.524-2.319C.743 11.37 0 9.76 0 8c0-3.866 3.582-7 8-7s8 3.134 8 7-3.582 7-8 7a9.06 9.06 0 0 1-2.347-.306c-.52.263-1.639.742-3.468 1.105z" />
    </svg>
    <br>
    <strong class="badge bg-primary" style="font-family: Georgia, 'Times New Roman', Times, serif;">
        <h1> EASY CHAT WITH FRIENDS </h1>
        <h1> AND FAMILY </h1>
    </strong>
    <img src="https://hackernoon.com/hn-images/1*mLE5ZxhtATxrwh20SL2Tlg.png" class=" rounded float-end mx-5"
        style="width:40%" alt="...">

</div>
{% else %}
<div class="container">

    <svg xmlns="http://www.w3.org/2000/svg" width="100" height="100" fill="currentColor" class="bi bi-chat my-5"
        viewBox="0 0 16 16">
        <path
            d="M2.678 11.894a1 1 0 0 1 .287.801 10.97 10.97 0 0 1-.398 2c1.395-.323 2.247-.697 2.634-.893a1 1 0 0 1 .71-.074A8.06 8.06 0 0 0 8 14c3.996 0 7-2.807 7-6 0-3.192-3.004-6-7-6S1 4.808 1 8c0 1.468.617 2.83 1.678 3.894zm-.493 3.905a21.682 21.682 0 0 1-.713.129c-.2.032-.352-.176-.273-.362a9.68 9.68 0 0 0 .244-.637l.003-.01c.248-.72.45-1.548.524-2.319C.743 11.37 0 9.76 0 8c0-3.866 3.582-7 8-7s8 3.134 8 7-3.582 7-8 7a9.06 9.06 0 0 1-2.347-.306c-.52.263-1.639.742-3.468 1.105z" />
    </svg>
    <br>
    <strong class="badge bg-primary" style="font-family: Georgia, 'Times New Roman', Times, serif;">
        <h1> EASY CHAT WITH FRIENDS </h1>
        <h1> AND FAMILY </h1>
    </strong>
    <img src="https://hackernoon.com/hn-images/1*mLE5ZxhtATxrwh20SL2Tlg.png" class=" rounded float-end mx-5"
        style="width:45%" alt="...">

</div>
{% endif %}



{% endblock navbar %}

templates/login.html
{% extends 'base.html' %}


{% block navbar %}

<body style=" background-color: #8a2be22b;">

</body>

<div class="container d-flex justify-content-center py-5 ">
    <div class=" card py-2 bg-light shadow p-3 mb-5 bg-body rounded  " style=" width: 40rem ">

        <form action=" /login" method="POST">
            <div class="container my-5 ">
                <div class="mb-5">
                    <label for="name" class="form-label">Name</label>
                    <input type="text" class="form-control" id="name" name="username" placeholder="Enter your name"
                        required>
                </div>
                <div class="mb-3">
                    <label for="pass" class="form-label">Password</label>
                    <input type="password" class="form-control" id="pass" name="pass" placeholder="Enter Password"
                        required>
                </div>
                <button class="btn btn-primary my-2" type="submit">Login</button>

            </div>
        </form>

    </div>
</div>
{% endblock navbar %}

templates/register.html
{% extends 'base.html' %}
{% block navbar %}

<body style=" background-color: #8a2be22b;">

</body>

<div class="container d-flex justify-content-center py-5" ">
    <div class=" card py-2 bg-light shadow-lg p-3 mb-5 bg-body rounded-3" style=" width: 40rem ">

    <form action=" /register" method="post">

        <div class="container my-5 ">
            <div class="mb-5">
                <label for="name" class="form-label">Name</label>
                <input type="text" class="form-control" name="username" id="name" placeholder="Enter your name"
                    required>
            </div>
            <div class="mb-3">
                <label for="pass" class="form-label">Password</label>
                <input type="password" class="form-control" id="pass" name="pass" placeholder="Enter Password" required>
            </div>
            <button class="btn btn-primary my-2" type="submit">Register</button>

        </div>
    </form>
    <span class=" text-center my-3">Already have an account ? Login in <a style="text-decoration:none" class=""
            href="/login">HERE</a> </span>
</div>
</div>

{% endblock navbar %}

templates/subjects.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <title>Rooms</title>
    <script src="/static/socket.js"></script>
    <link rel="stylesheet" href="/static/chat.css">

</head>

<body>
    <!-- Navbar -->
    <nav class="navbar sticky-top navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
            <a class="navbar-brand" href="/">
                <h3 id="chat-clicked" style="font-family:cursive;"> CHAT </h3>
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">

                {% if 'username' in session : %}
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="/rooms">
                            <h3 class="room-click" style="font-family:cursive; "> Rooms </h3>
                        </a>
                    </li>
                </ul>
                <form class="d-flex px-1">
                    <a id="logout-now" class="btn btn-outline-danger " type="submit" style="font-family:cursive;"
                        href="/logout">Logout</a>
                </form>

                {% else %}

                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="/login">
                            <h3 class="room-click" style="font-family:cursive;"> Rooms </h3>
                        </a>
                        <!-- onclick="LeaveRoom()" -->
                    </li>
                </ul>
                <form class="d-flex">
                    <a class="btn btn-outline-success" type="submit" style="font-family:cursive;"
                        href="/login">Login</a>
                </form>
                <form class="d-flex px-1">
                    <a class="btn btn-outline-danger" type="submit" style="font-family:cursive;"
                        href="/register">Register</a>
                </form>
                {% endif %}

            </div>
        </div>
    </nav>

    <title>Rooms</title>

    <body style=" background-color: #292323da;"></body>



    <div class="container ">
        <div class="row ">
            <div class="col container">
                <div class="badge bg-light  my-3 ">
                    <h3 class="  text-capitalize text-info"> <a href="/create_sub" style="text-decoration: none;">Create
                            your own
                            room HERE</a> </h3>
                </div>
            </div>
            <div class="col">
                <div class="input-group my-3">
                    <input id="input-val" type="text" class="form-control " placeholder="search room here ">
                    <button class="btn btn-danger" type="submit">Search</button>
                </div>
            </div>
        </div>


        <h2 class="container py-4 text-center text-light ">Select a Room</h2>


        {% if subject_data is defined %}


        <div id="rooms-Name" class="card-columns ">

            {% for subject in subject_data %}

            {% if subject[2] == 0 %}
            <a class="tar" style="text-decoration:none" href={{url_for("sub_route.enter_room" , id=subject[0])}}>
                <div class="card d-lg-inline-flex mx-2 my-2 tar1">
                    <img class="card-img-top "
                        src="https://i.pinimg.com/originals/f9/9e/0b/f99e0b812f21d685b09a01fa60ec1cd3.png" height="200"
                        alt="Card image cap">
                    <div class="card-body shadow bg-body rounded">
                        <h5 class="card-title  ">
                            <p class="badge bg-info text-dark inside-room4" onclick="JoinRoom()">{{subject[1]}}</p>
                        </h5>
                    </div>
                </div>
            </a>
            {% else %}
            <a class="tar" style=" text-decoration:none" href={{url_for("sub_route.enter_room" , id=subject[0])}}>
                <div class="card d-lg-inline-flex mx-2 my-2 tar1">
                    <img class="card-img-top "
                        src="https://i.pinimg.com/originals/f9/9e/0b/f99e0b812f21d685b09a01fa60ec1cd3.png" height="200"
                        alt="Card image cap">
                    <div class="card-body ">
                        <h5 class="card-title ">
                            <p class="badge bg-info text-dark inside-room4" onclick="JoinRoom()">{{subject[1]}} <span
                                    class="text-danger "> 🔐</span></p>
                        </h5>
                    </div>
                </div>
            </a>

            {% endif %}


            {% endfor %}
        </div>
        {% endif %}

    </div>


    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/socket.io/4.0.1/socket.io.js"
        integrity="sha512-q/dWJ3kcmjBLU4Qc47E4A9kTB4m3wuTY7vkFJDTZKjTs8jhyGQnaUrxa0Ytd0ssMZhbNua9hE+E7Qv1j+DyZwA=="
        crossorigin="anonymous"></script>


</body>

</html>